RealTalk/Models/AddCommentToPost.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RealTalk.Models
{
    public class AddCommentToPost
    {
        public List<Comment> tags { get; set; }
        public string commentToAdd { get; set; }
        public int selectedPost { get; set; }
        public AddCommentToPost()
        {
            tags = new List<Comment>();
        }
    }
}

RealTalk/Models/AddTagToPost.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RealTalk.Models
{
    public class AddTagToPost
    {
        public List<Tag> tags { get; set; }
        public int selectedTag { get; set; }
        public int selectedPost { get; set; }
        public AddTagToPost()
        {
            tags = new List<Tag>();
        }
    }
}

RealTalk/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RealTalk.Models
{
    public class Post
    {
        [Key]
        public int Id { get; set; }

        public String Title { get; set; }
        
        public String Content { get; set; }

        public ApplicationUser User { get; set; }
        
        public String Author { get; set; }
        public virtual List<Tag> Tags { get; set; }

        public String TagsText { get; set; }

        public virtual List<Comment> Comments { get; set; }

        public bool Flagged { get; set; }

        public Post()
        {
            Tags = new List<Tag>();
            Comments = new List<Comment>();
            Flagged = false;
        }
    }
}

RealTalk/Controllers/PostsController.cs
using Microsoft.AspNet.Identity;
using RealTalk.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace RealTalk.Controllers
{
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Posts
        public ActionResult Index()
        {
            return View(db.Posts.ToList());
        }

        [Authorize(Roles = "Moderator")]
        public ActionResult FlaggedPosts()
        {
            return View(db.Posts.ToList().Where(post => post.Flagged == true));
        }

        public ActionResult FlagPost(int id)
        {
            Post post = db.Posts.Find(id);
            if(post.Flagged == false)
            {
                post.Flagged = true;
                db.SaveChanges();
            }

            return View("ThankYouReport");

        }
        public ActionResult Search(string tagName)
        {
            IEnumerable<string> tagNames = db.Tags.ToList().Select(t => t.Name);
            if (tagNames.Contains(tagName))
            {
                Tag tag = db.Tags.Where(t => t.Name == tagName).FirstOrDefault();
                Boolean flag = db.Posts.Find(1).Tags.Contains(tag);
                IEnumerable<Post> filteredPosts = db.Posts.ToList().Where(p => p.Tags.Contains(tag));
                if(filteredPosts.Count() == 0)
                {
                    return RedirectToAction("NoPostFound");
                }
                Random r = new Random();
                System.Diagnostics.Debug.WriteLine(filteredPosts.ToString());

                int postIndex = r.Next(filteredPosts.Count());
                int id = filteredPosts.ElementAt(postIndex).Id;
                return RedirectToAction("Details/" + id);
            }
            else if (tagName == null || tagName == "")
            {
                int postsCount = db.Posts.Count();
                Random r = new Random();
                int postIndex = r.Next(postsCount);
                int id = db.Posts.ToList().ElementAt(postIndex).Id;
                return RedirectToAction("Details/" + id);
            }
            else
                return RedirectToAction("NoPostFound");//ili custom error view
        }

        public ActionResult RandomPost()
        {
            int postsCount = db.Posts.Count();
            Random r = new Random();
            int postIndex = r.Next(postsCount);
            int id = db.Posts.ToList().ElementAt(postIndex).Id;
            return RedirectToAction("Details/" + id);
        }

        public ActionResult NoPostFound()
        {
            return View();
        }

        [Authorize(Roles = "Moderator")]
        public ActionResult RemoveFlag(int? id)
        {
            Post post = db.Posts.Find(id);
            if(post != null)
            {
                post.Flagged = false;
                db.SaveChanges();
            }
            
            return RedirectToAction("FlaggedPosts");
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);

            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,Title,Content")] Post post)
        {
            if (ModelState.IsValid)
            {
                string username = User.Identity.GetUserName();
                ApplicationUser user = db.Users.Where(u => u.UserName == username).FirstOrDefault();
                post.User = user;
                post.Author = username;
                db.Posts.Add(post);
                db.SaveChanges();
                System.Diagnostics.Debug.WriteLine("Saved post: "+post);
                return RedirectToAction("Details/" + post.Id);
            }

            return View(post);
        }

        [Authorize]
        public ActionResult AddTagToPost(int id)
        {
            AddTagToPost model = new AddTagToPost();
            model.selectedPost = id;
            model.tags = db.Tags.ToList();
            ViewBag.PostTitle = db.Posts.Find(id).Title;
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddTagToPost(AddTagToPost model)
        {
            var tag = db.Tags.Find(model.selectedTag);
            var post = db.Posts.Find(model.selectedPost);
            post.Tags.Add(tag);
            db.SaveChanges();
            return RedirectToAction("Details/" + post.Id);
        }

        [Authorize]
        public ActionResult AddCommentToPost(int id, string commentContent)
        {
            AddCommentToPost model = new AddCommentToPost();
            model.selectedPost = id;
            //model.tags = db.Tags.ToList();
            ViewBag.PostTitle = db.Posts.Find(id).Title;
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddCommentToPost(AddCommentToPost model)
        {
            string username = User.Identity.GetUserName();
            ApplicationUser user = db.Users.Where(u => u.UserName == username).FirstOrDefault();
            Comment comment = new Comment();
            comment.User = user;
            comment.Author = username;
            comment.Content = model.commentToAdd;
            db.Comments.Add(comment);
            db.SaveChanges();
            var post = db.Posts.Find(model.selectedPost);
            post.Comments.Add(comment);
            db.SaveChanges();
            return RedirectToAction("Details/" + post.Id);
        }


        // GET: Posts/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Title,Content")] Post post)
        {
            if (ModelState.IsValid)
            {
                string username = User.Identity.GetUserName();
                post.Author = username;
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details/" + post.Id);
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/@username ??
        [Authorize]
        public ActionResult UserPosts()
        {
            String username = User.Identity.GetUserName();
            ApplicationUser user = db.Users.Where(u => u.UserName == username).FirstOrDefault();
            IEnumerable<Post> filteredPosts = db.Posts.ToList().Where(p => p.Author.Trim().Equals(username.Trim()));
            return View(filteredPosts.ToList());
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            //first remove post's comments
            db.Comments.RemoveRange(post.Comments);
            db.SaveChanges();
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RealTalk/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RealTalk.Models;

namespace RealTalk.Controllers
{
    public class TagsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tags
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: Tags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // GET: Tags/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        // GET: Tags/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RealTalk/Views/Posts/AddCommentToPost.cshtml
@model RealTalk.Models.AddCommentToPost
@{
    ViewBag.Title = "AddCommentToPost";
}

@*<h2>AddCommentToPost</h2>*@
<div class="text-light">
    <h2>Add Comment To Post with title:</h2>
    <h4>@ViewBag.PostTitle</h4>


    @using (Html.BeginForm("AddCommentToPost", "Posts"))
    {
        <div class="form-group txtdark">
            @Html.TextAreaFor(m => m.commentToAdd, new { @class = "form-control" })
        </div>
        <button type="submit" class="btn btn-danger">Add</button>

        @Html.HiddenFor(m => m.selectedPost)
    }

</div>

RealTalk/Views/Posts/AddTagToPost.cshtml
@model RealTalk.Models.AddTagToPost
@{
    ViewBag.Title = "AddTagToPost";
}
<div class="text-light">

    <div class="box2 sb3 text-left txtdark">

        @using (Html.BeginForm("AddTagToPost", "Posts"))
        {
            <h4 class=""><strong>Add Tag To Post with title: @ViewBag.PostTitle</strong></h4><br />
            <div class="form-group txtdark">
                @Html.DropDownListFor(m => m.selectedTag, new SelectList(Model.tags, "Id", "Name"))
            </div>
            <button type="submit" class="btn btn-danger">Add</button>

            @Html.HiddenFor(m => m.selectedPost)
        }
        <br />
        @Html.ActionLink("Add a new tag", "Create", "Tags", null, null)


    </div>
    </div>

RealTalk/Views/Posts/Create.cshtml
@model RealTalk.Models.Post

@{
    ViewBag.Title = "Create a post";
}

@*<head>
        <link href="CreatePost.css" rel="stylesheet" type="text/css" />

    </head>*@

@*<style>
        body {
        }

        .random-class {
            border: solid 10px yellow;
        }

        .container {
            text-align: center;
        }

        .center-box {
            width: 500px;
        }
    </style>*@

<!--Create-->
<div class="col-12 text-center">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="box1 sb2 text-left txtdark">
            <h4 class=""><strong>Create a new post</strong></h4><br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="mymultitextboxclass">
                    @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>


            @*<div class="form-group">
                @Html.LabelFor(model => model.TagsText, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.TagsText, new { htmlAttributes = new { @class = "form-control" } })
            </div>*@

            <!--Submit-->
            <button type="submit" class="btn btn-outline-light my-2 my-sm-0">Create a post</button> <br><br><br>
        </div>
    }
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RealTalk/Views/Posts/Delete.cshtml
@model RealTalk.Models.Post

@{
    ViewBag.Title = "Delete";
}
<div class="text-light">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Post</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Content)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Content)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    </div>

RealTalk/Views/Posts/Details.cshtml
@model RealTalk.Models.Post

@{
    ViewBag.Title = "Details";  
}
<div class="text-light">

    <div class="text-center">
        <div class="box1 sb2 text-left">

            <h4 class="txtdark">@Html.DisplayFor(model => model.Title)</h4>
            <h6 class="txtdark">By user: @Html.DisplayFor(model => model.Author)</h6>

            <br />
            <p> @Html.DisplayFor(model => model.Content)</p>

            <div class="row">
                Tags:
                @foreach (var item in Model.Tags)
                {
                    <a href="/Tags/Details/@item.Id">#@item.Name</a>
                }
            </div>
            <br />

            @if (User.Identity.IsAuthenticated && (ViewContext.HttpContext.User.Identity.Name == Model.Author))
            {
                @Html.ActionLink("Edit Post", "Edit", new { id = Model.Id }, new { @style = "color:#2E294E !important; font-weight:bold;" })
                <span style="color:#2E294E !important"> | </span>
                @Html.ActionLink("Add a New Tag", "AddTagToPost", new { id = Model.Id }, new { @style = "color:#2E294E !important; font-weight:bold;" })

            }
            else
            {
                @Html.ActionLink("Report This Post", "FlagPost", "Posts", new { id = Model.Id }, new { @style = "color:#2E294E !important; font-weight:bold;" })
            }


        </div>
        @*<button class="btn my-2 my-sm-0 text-dark">Not satisfied with this post? Click to try again!</button>*@
        <button class="btn my-2 my-sm-0 text-dark">@Html.ActionLink("Not satisfied with this post? Click to try again!", "RandomPost", "Posts", null, new { @style = "color:#2E294E !important; font-weight:bold;" })</button>
        <br><br><br>
        <br />
        <h3 class="text-center">Comments:</h3>
        <div>
            @foreach (var item in Model.Comments)
            {
                <div class="box2 sb1 text-right">
                    <div>@item.Content</div>
                    <div><strong> By user: @item.Author</strong></div>

                </div>
                <br />
            }
        </div>

        <button class="btn my-2 my-sm-0 text-dark">@Html.ActionLink("Add a Comment", "AddCommentToPost", new { id = Model.Id }, new { @style = "color:#2E294E !important; font-weight:bold;" })</button>
        <br />
        <br />

    </div>
    <p class="text-center">        
        @Html.ActionLink("Back to Home", "Index", "Home")
    </p>
    </div>

RealTalk/Views/Posts/Edit.cshtml
@model RealTalk.Models.Post

@{
    ViewBag.Title = "Edit";
}
<div class="text-light">



    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="box1 sb2 text-left txtdark">
            <div class="form-horizontal">
                <h4>Edit post</h4>
                <br />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
            </div>
            }
        </div>
        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

RealTalk/Views/Posts/FlaggedPosts.cshtml
@model IEnumerable<RealTalk.Models.Post>

@{
    ViewBag.Title = "FlaggedPosts";
}

<h2 class="text-light">Flagged Posts</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<div class="row ">
    <table class="table text-light mt-4 ">
        <thead class="bgblue txtdark">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Content)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Content)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                        @Html.ActionLink("Remove Flag", "RemoveFlag", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

RealTalk/Views/Posts/Index.cshtml
@model IEnumerable<RealTalk.Models.Post>

@{
    ViewBag.Title = "Index";
}

<div class="text-light">
    <h2>Posts</h2>

    <p>
        <button class="btn my-2 my-sm-0" type="submit">@Html.ActionLink("Create a New Post", "Create", "Posts", null, new { @style = "color:#2E294E !important; font-weight:bold;" })</button>
        <br />
    </p>

    @*<a href="#" class="btn btn-primary" id="export-btn">Find a random post</a>
        <input type="text" id="tagName">*@

    <div class="row ">
        <table class="table text-light mt-4 ">
            <thead class="bgblue txtdark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Content)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Content)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                            @Html.ActionLink("Add a Tag", "AddTagToPost", new { id = item.Id })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RealTalk/Views/Posts/NoPostFound.cshtml
@{
    ViewBag.Title = "No Post Found";
}

<div class="text-light">

    <div class="text-center">
        <br />
        <br />
        <br />
        <h2>We're sorry but no posts were found with this tag.</h2>
        <br />
        <button class="btn my-2 my-sm-0 text-dark">@Html.ActionLink("Give Me a Random Post", "RandomPost", "Posts", null, new { @style = "color:#2E294E !important; font-weight:bold;" })</button>
        <button class="btn my-2 my-sm-0 text-dark">@Html.ActionLink("Back to Homepage", "Index", "Home", null, new { @style = "color:#2E294E !important; font-weight:bold;" })</button>
        <br />
        <br />
    </div>
</div>

RealTalk/Views/Posts/ThankYouReport.cshtml
@{
    ViewBag.Title = "ThankYouReport";
}

<div class="text-light">

    <div class="text-center">
        <br />
        <br />
        <br />
        <h2>Thank you for reporting this post</h2>
        <h4>Our team will examine if it violates our guidelines and act accordingly.</h4>
        <br />
        <button class="btn my-2 my-sm-0 text-dark">@Html.ActionLink("Give Me a Random Post", "RandomPost", "Posts", null, new { @style = "color:#2E294E !important; font-weight:bold;" })</button>
        <button class="btn my-2 my-sm-0 text-dark">@Html.ActionLink("Back to Homepage", "Index", "Home", null, new { @style = "color:#2E294E !important; font-weight:bold;" })</button>
        <br />
        <br />
    </div>
</div>

RealTalk/Views/Posts/UserPosts.cshtml
@model IEnumerable<RealTalk.Models.Post>

@{
    ViewBag.Title = "UserPosts";
}

<div class="text-light">
    <h1><strong>User Posts</strong></h1>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    @*<a href="#" class="btn btn-primary" id="export-btn">Find a random post</a>
        <input type="text" id="tagName">*@

    <div class="row ">
        <table class="table text-light mt-4 ">
            <thead class="bgblue txtdark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Content)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Content)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
                            @Html.ActionLink("Add a Tag", "AddTagToPost", new { id = item.Id })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>